import { useEffect, useRef, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { createExpense,deleteExpense,getExpenses,getFinanceSummary,type Expense,type FinanceSummary } from '../../services/financeService';
import { updateBarberExpense } from '../../services/barberService';
import { localDate,money } from './formatters';
import styles from './BarberApp.module.css';
export function FinanceiroPanel(){
  const [period,setPeriod]=useState(localDate().slice(0,7));
  const [summary,setSummary]=useState<(FinanceSummary & {received_deposits?:string})|null>(null);
  const [expenses,setExpenses]=useState<Expense[]>([]);
  const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('');const [revision,setRevision]=useState(0);
  const [editor,setEditor]=useState<'new'|number|null>(null);const [name,setName]=useState('');const [amount,setAmount]=useState('');const [date,setDate]=useState(localDate());
  const [pending,setPending]=useState(false);const [formError,setFormError]=useState('');const [deleting,setDeleting]=useState<number|null>(null);const saving=useRef(false);
  useEffect(()=>{let active=true;setLoading(true);setError('');setSummary(null);setExpenses([]);const [year,month]=period.split('-').map(Number);
    Promise.all([getFinanceSummary(year,month),getExpenses(year,month)]).then(([data,items])=>{if(active){setSummary(data);setExpenses(items);}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Falha ao carregar o financeiro.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};
  },[period,revision]);
  function open(expense?:Expense){setEditor(expense?.id??'new');setName(expense?.name??'');setAmount(expense?.amount??'');setDate(expense?.incurred_on??(period===localDate().slice(0,7)?localDate():`${period}-01`));setFormError('');}
  async function save(e:React.FormEvent){e.preventDefault();if(saving.current||editor===null)return;const value=Number(amount.replace(',','.'));if(!name.trim()||!Number.isFinite(value)||value<=0){setFormError('Informe uma descrição e um valor maior que zero.');return;}saving.current=true;setPending(true);setFormError('');
    try{const payload={name:name.trim(),amount:value.toFixed(2),incurred_on:date};if(editor==='new')await createExpense(payload);else await updateBarberExpense(editor,payload);setEditor(null);setPeriod(date.slice(0,7));setRevision(v=>v+1);setMessage(`Custo salvo em ${new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR')}.`);}catch(e){setFormError(e instanceof Error?e.message:'Não foi possível salvar o custo.');}finally{saving.current=false;setPending(false);}}
  async function remove(id:number){if(saving.current)return;saving.current=true;setPending(true);setFormError('');try{await deleteExpense(id);setDeleting(null);setRevision(v=>v+1);setMessage('Custo removido.');}catch(e){setFormError(e instanceof Error?e.message:'Não foi possível remover.');}finally{saving.current=false;setPending(false);}}
  return <div className={styles.stack}>
    <section className={styles.panel} aria-busy={loading}><div className={styles.panelHead}><div><h2 className={styles.panelTitle}>Resultado do período</h2><p className={styles.sectionHint}>Valores dos atendimentos concluídos e custos registrados.</p></div><label className={styles.fieldLabel}>Mês do relatório<input type="month" value={period} onChange={e=>{if(e.target.value){setPeriod(e.target.value);setMessage('');setDeleting(null);}}}/></label></div>
      {message&&<p className={styles.toastOk} role="status">{message}</p>}{loading?<p role="status">Carregando relatório…</p>:error?<p className={styles.toastErr} role="alert">{error}<button className={styles.btnGhost} onClick={()=>setRevision(v=>v+1)}>Tentar novamente</button></p>:summary&&<>
        <div className={styles.finTiles}><article className={styles.finTile}><small>Atendimentos concluídos</small><strong className={styles.finValue}>{money(summary.revenue)}</strong><small>{summary.completed_count} atendimentos</small></article><article className={styles.finTile}><small>Custos registrados</small><strong className={styles.finValue}>{money(summary.expenses)}</strong><small>{expenses.length} lançamentos</small></article><article className={styles.finTile}><small>Resultado estimado</small><strong className={Number(summary.profit)<0?styles.finValueNeg:styles.finValue}>{money(summary.profit)}</strong><small>Atendimentos menos custos</small></article><article className={styles.finTile}><small>Margem estimada</small><strong className={styles.finValue}>{Number(summary.revenue)>0?`${summary.margin}%`:'—'}</strong><small>{Number(summary.revenue)>0?'Sobre os atendimentos concluídos':'Sem atendimentos no período'}</small></article></div>
        <p className={styles.sectionHint}>Este resultado não representa dinheiro efetivamente recebido nem um fechamento de caixa.</p>
        {summary.received_deposits!==undefined&&<div className={styles.depositSummary}><strong>Sinais recebidos: {money(summary.received_deposits)}</strong><p>Sinais aprovados neste mês, descontados os estornos já registrados. O restante dos atendimentos não está incluído.</p></div>}
        {summary.series.length>0&&<details><summary className={styles.detailsTitle}>Comparar os últimos seis meses</summary><div className={styles.tableWrap}><table className={styles.finTable}><caption>Produção e custos por mês</caption><thead><tr><th scope="col">Mês</th><th scope="col">Atendimentos</th><th scope="col">Custos</th><th scope="col">Resultado</th></tr></thead><tbody>{summary.series.map(p=><tr key={p.label}><th scope="row">{p.label}</th><td>{money(p.revenue)}</td><td>{money(p.expenses)}</td><td>{money(p.profit)}</td></tr>)}</tbody></table></div></details>}
        {summary.breakdown.length>0&&<details><summary className={styles.detailsTitle}>Valores por serviço</summary><div className={styles.rows}>{summary.breakdown.map(r=><div className={styles.rowTop} key={r.name}><span>{r.name} · {r.count} atendimentos</span><strong>{money(r.total)}</strong></div>)}</div></details>}
      </>}
    </section>
    <section className={styles.panel}><div className={styles.panelHead}><h2 className={styles.panelTitle}>Custos do mês</h2><button className={styles.btnGhost} onClick={()=>open()} disabled={pending}><Plus size={16}/> Lançar custo</button></div>
      {formError&&<p className={styles.toastErr} role="alert">{formError}</p>}
      {editor!==null&&<form className={styles.editorForm} onSubmit={save}><h3>{editor==='new'?'Novo custo':'Editar custo'}</h3><fieldset className={styles.formBoundary} disabled={pending}><label className={styles.fieldLabel}>Descrição do custo<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: aluguel, energia ou produtos"/></label><div className={styles.formRow}><label className={styles.fieldLabel}>Valor do custo (R$)<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className={styles.fieldLabel}>Data do custo<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{date.slice(0,7)!==period&&<p>Ao salvar, o relatório abrirá o mês da data escolhida.</p>}<div className={styles.pairActions}><button className={styles.btn}>{pending?'Salvando…':'Salvar custo'}</button><button type="button" className={styles.btnGhost} onClick={()=>setEditor(null)}>Cancelar</button></div></fieldset></form>}
      {!loading&&!error&&expenses.length===0&&<p className={styles.sectionHint}>Nenhum custo registrado neste mês.</p>}
      <div className={styles.rows}>{expenses.map(e=><article className={styles.row} key={e.id}><div className={styles.rowTop}><div className={styles.rowMain}><strong>{e.name}</strong><small>{new Date(`${e.incurred_on}T12:00:00`).toLocaleDateString('pt-BR')}</small></div><strong>{money(e.amount)}</strong><div className={styles.rowActions}><button className={styles.iconBtn} aria-label={`Editar custo ${e.name}`} onClick={()=>open(e)} disabled={pending}><Pencil size={16}/></button><button className={styles.iconBtnDanger} aria-label={`Remover custo ${e.name}`} onClick={()=>setDeleting(e.id)} disabled={pending}><Trash2 size={16}/></button></div></div>{deleting===e.id&&<div className={styles.inlineAction}><p>Remover {e.name}, de {money(e.amount)}?</p><div className={styles.pairActions}><button className={styles.btnDanger} disabled={pending} onClick={()=>void remove(e.id)}>Confirmar remoção</button><button className={styles.btnGhost} disabled={pending} onClick={()=>setDeleting(null)}>Manter custo</button></div></div>}</article>)}</div>
    </section>
  </div>;
}
